"""Ontario Hydro One standard TOU band function. Pure and unit-tested.

Off-peak: weekdays 19:00-07:00, all weekend, Ontario statutory holidays.
Summer (May 1 - Oct 31): on-peak 11:00-17:00, mid-peak fills 07-11 and 17-19.
Winter (Nov 1 - Apr 30): on-peak 07:00-11:00 and 17:00-19:00, mid-peak 11-17.

Holidays come from the data file src/solarmon/data/ontario_holidays.json
(generated by scripts/gen_holidays.py; extend it when the range runs out).
"""

from __future__ import annotations

import json
import logging
from datetime import date, datetime
from functools import lru_cache
from pathlib import Path
from typing import Literal
from zoneinfo import ZoneInfo

Band = Literal["off_peak", "mid_peak", "on_peak"]

HOLIDAYS_FILE = Path(__file__).parent / "data" / "ontario_holidays.json"

log = logging.getLogger("tou")


@lru_cache(maxsize=1)
def load_holidays() -> frozenset[date]:
    raw = json.loads(HOLIDAYS_FILE.read_text(encoding="utf-8"))
    return frozenset(date.fromisoformat(d) for d in raw)


def band(dt: datetime, holidays: frozenset[date] | None = None) -> Band:
    """TOU band for a LOCAL (America/Toronto) datetime."""
    if holidays is None:
        holidays = load_holidays()
    d = dt.date()
    if d.year > max(h.year for h in holidays):
        log.warning("date %s is beyond the holiday data file; regenerate it", d)
    if dt.weekday() >= 5 or d in holidays:
        return "off_peak"
    h = dt.hour
    if h >= 19 or h < 7:
        return "off_peak"
    summer = 5 <= dt.month <= 10  # seasonal swap on May 1 / Nov 1
    if summer:
        return "on_peak" if 11 <= h < 17 else "mid_peak"
    return "on_peak" if (7 <= h < 11 or 17 <= h < 19) else "mid_peak"


def band_for_ts(ts: int, tz: str = "America/Toronto") -> Band:
    """TOU band for a UTC epoch timestamp."""
    return band(datetime.fromtimestamp(ts, ZoneInfo(tz)))
